"""create table models

Revision ID: 460791116a66
Revises: b28a871ca69b
Create Date: 2023-10-28 12:39:58.120085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460791116a66'
down_revision = 'b28a871ca69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
